### ISSUE TITLE
Need to add more camera streams to the code

### ISSUE THREAD

**Issue by karanveersingh5623** [RedisGears/EdgeRealtimeVideoAnalytics#28]
Hi , How can we add more simultaneous camera streams or video playback streams to the environment?
In gears.py , the camera:0 is hardcoded. How can we handle multiple cameras when executing gears.py through redis gears in init.py .

**Comment by MeirShpilraien** [comment]
The stream reader can register to prefix of streams so instead `register("camera:0")` you can do `register(prefix="camera:*")`. This way the image analysis code will be triggered for each stream with the prefix `camera:`

**Comment by MeirShpilraien** [comment]
https://oss.redislabs.com/redisgears/readers.html#streamreader

**Comment by karanveersingh5623** [comment]
Thanks for the info buddy but its throwing exception with prefix .... check the below trace . Any way forward .
`Jamess-Mac-Pro:Redisai_edgeAnalytics_old karanveer$ docker ps -a
CONTAINER ID        IMAGE                                                 COMMAND                  CREATED             STATUS                      PORTS                    NAMES
4b1594874f54        redisai_edgeanalytics_old_server                      "python3 server.py -…"   18 seconds ago      Up 17 seconds               0.0.0.0:5000->5000/tcp   redisai_edgeanalytics_old_server_1
dd09fb40d6ae        redisai_edgeanalytics_old_capture                     "python3 capture.py …"   18 seconds ago      Up 17 seconds                                        redisai_edgeanalytics_old_capture_1
6a0afc8c956a        redislabs/prometheus-redistimeseries-adapter:master   "/adapter/redis-ts-a…"   19 seconds ago      Up 18 seconds               0.0.0.0:9201->9201/tcp   redisai_edgeanalytics_old_prometheus-redistimeseries-adapter_1
7e9f389a313b        ajeetraina/grafana-redisedge                          "/run.sh"                19 seconds ago      Up 18 seconds               0.0.0.0:3000->3000/tcp   redisai_edgeanalytics_old_grafana_1
74b9038b5bbd        redisai_edgeanalytics_old_init                        "python3 init.py --u…"   19 seconds ago      Exited (1) 17 seconds ago                            redisai_edgeanalytics_old_init_1
0c8a75900ab3        redisai_edgeanalytics_old_redisedge                   "docker-entrypoint.s…"   20 seconds ago      Up 19 seconds               0.0.0.0:6379->6379/tcp   redisai_edgeanalytics_old_redisedge_1
f2cf80dcbae4        redisai_edgeanalytics_old_prometheus                  "/bin/prometheus --c…"   20 seconds ago      Up 19 seconds               0.0.0.0:9090->9090/tcp   redisai_edgeanalytics_old_prometheus_1
Jamess-Mac-Pro:Redisai_edgeAnalytics_old karanveer$ docker logs 74b9038b5bbd
Loading model - b'OK'
Loading script - b'OK'
Creating timeseries keys and downsampling rules - [b'OK', b'OK', b'OK', b'OK', b'OK', b'OK', b'OK', b'OK', b'OK', b'OK', b'OK', b'OK', b'OK', b'OK', b'OK', b'OK', b'OK', b'OK', b'OK', b'OK', b'OK', b'OK', b'OK', b'OK', b'OK', b'OK', b'OK', b'OK']
Traceback (most recent call last):
  File "init.py", line 70, in <module>
    res = conn.execute_command('RG.PYEXECUTE', gear)
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 775, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 789, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 642, in read_response
    raise response
redis.exceptions.ResponseError: deco() got an unexpected keyword argument 'prefix'
Loading gear - Jamess-Mac-Pro:Redisai_edgeAnalytics_old karanveer$ 
`

**Comment by MeirShpilraien** [comment]
Seems like a very old version of RedisGears, try to pass it without a named argument like `register("camera:*")`

**Comment by karanveersingh5623** [comment]
Did that as well , no exceptions but nothing shows up in grafana like boxes and people counting , it streams a plain video

**Comment by karanveersingh5623** [comment]
do we need to change anything in def storeResults(x) , there are multiple entries for camera:0

**Comment by MeirShpilraien** [comment]
Can you share the output of RG.DUMPREGISTRATIONS? Also can you share the RedisGears version you are using?

**Comment by MeirShpilraien** [comment]
We have discord for instant messaging, maybe it will be easier to chat there? https://discord.com/invite/6yaVTtp

**Comment by karanveersingh5623** [comment]
pinged you as karanveer
