### ISSUE TITLE
redislabs/redisedge:latest is very old , info modules shows invalid versions and various other issues

### ISSUE THREAD

**Issue by karanveersingh5623** [RedisGears/EdgeRealtimeVideoAnalytics#31]
Hi , tried changing the Dockerfile under redisedge folder , below are the contents , one of the issues is python3 virtual environment is not getting picked up when running RG.PYEXECUTE gears in init.py . 

`
FROM redislabs/redismod:latest

ENV DEPS "python python3-pip python3-setuptools libglib2.0-0 libsm6 libxrender1 libxext6 libgomp1"
RUN set -ex; \
    apt-get update; \
    apt-get install -y --no-install-recommends $DEPS;

RUN set -ex; \
    pip3 install -U pipenv;

ADD ./requirements.txt /tmp/requirements.txt
RUN set -ex; \
    cd /var/opt/redislabs/modules/rg/python3; \
    pipenv run pip3 install -r /tmp/requirements.txt;

ADD ./redisedge.conf /usr/local/etc/redisedge.conf

CMD ["/usr/local/etc/redisedge.conf"]`

Below is the error trace of init.py docker container logs 

`$ docker logs 6b01e31dea1e
Loading model - b'OK'
Loading script - b'OK'
Creating timeseries keys and downsampling rules - [b'OK', b'OK', b'OK', b'OK', b'OK', b'OK', b'OK', b'OK', b'OK', b'OK', b'OK', b'OK', b'OK', b'OK', b'OK', b'OK', b'OK', b'OK', b'OK', b'OK', b'OK', b'OK', b'OK', b'OK', b'OK', b'OK', b'OK', b'OK']
Traceback (most recent call last):
  File "init.py", line 72, in <module>
    res = conn.execute_command('RG.PYEXECUTE', gear)
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 775, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 789, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 642, in read_response
    raise response
redis.exceptions.ResponseError: ['Traceback (most recent call last):\n', '  File "<string>", line 3, in <module>\n', "ModuleNotFoundError: No module named 'cv2'\n"]`

**Comment by karanveersingh5623** [comment]
Also with building up with docker-compose , below is the trace seen for redisedge Dockerfile 
`Step 6/8 : RUN set -ex;     cd /var/opt/redislabs/modules/rg/python3;     pipenv run pip3 install -r /tmp/requirements.txt;
 ---> Running in bf49cce7aa5f
+ cd /var/opt/redislabs/modules/rg/python3
+ pipenv run pip3 install -r /tmp/requirements.txt
Warning: the environment variable LANG is not set!
We recommend setting this in ~/.profile (or equivalent) for proper expected behavior.
Creating a virtualenv for this project...
Pipfile: /var/opt/redislabs/modules/rg/python3/Pipfile
Using /usr/bin/python3 (3.7.3) to create virtualenv...
⠧ Creating virtual environment...created virtual environment CPython3.7.3.final.0-64 in 1147ms
  creator CPython3Posix(dest=/root/.local/share/virtualenvs/python3-AuMyyDKG, clear=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/root/.local/share/virtualenv)
    added seed packages: pip==20.2.4, setuptools==50.3.2, wheel==0.35.1
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator

✔ Successfully created virtual environment! 
Virtualenv location: /root/.local/share/virtualenvs/python3-AuMyyDKG
Creating a Pipfile for this project...`
